export default {
  $theme: 'dark',
  $background: '#1d2c3f',
  $text: '#ffffff',
  $headerBackground: '#1d2c3f',
  $headerBorder: '#0b1e35',
  $buttonBackground: '#ea9e6c',
  $link: '#6cb7f9',
  $headerText: '#ffffff',
  $inputBorder: '#e7f1f6',
  $backButton: '#ffffff',
  $questionText: '#ffffff',
  $label: '#ffffff',
  $profileBlockBackground: '#0b1e35',
  $messageBackground: '#0b1e35',
  $messageText: '#ffffff',
};
